/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;


import java.io.File;
import java.io.FileNotFoundException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        App application = new App();

        Path filePath = Paths.get("resources/gates.js");

        String errorMessages = application.javascriptLinter(filePath);
        System.out.println(errorMessages);
    }

    public String javascriptLinter(Path pathName) {

        String displayError = "";

        try {

            int currentLine = 1;

            Scanner scLinter = new Scanner(new File(pathName.toUri()));

            while (scLinter.hasNext()) {

                String nextLine = scLinter.nextLine();

                if (hasError(nextLine)) {
                    displayError += String.format("Line %d: Missing semicolon.\n", currentLine);
                }

                currentLine++;
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

        return displayError;

    }

    public boolean hasError(String lineOfCode) {

        boolean errorValue = true;

        if (lineOfCode.isEmpty()) {
            errorValue = false;
        }

        if (!lineOfCode.isEmpty()) {

            if (lineOfCode.endsWith(";")) {
                errorValue = false;
            }

            if (lineOfCode.startsWith("//")) {
                errorValue = false;
            }

            if (lineOfCode.endsWith("{")) {
                errorValue = false;
            }

            if (lineOfCode.endsWith("}")) {
                errorValue = false;
            }

            if (lineOfCode.contains("if")) {
                errorValue = false;
            }

            if (lineOfCode.contains("else")) {
                errorValue = false;
            }
        }

        return errorValue;
    }
}
