/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test
    public void testRoll() {
        int numberOfRolls = 2;
        assertEquals("Roll method should return array of length 2",2, Library.roll(2).length);
    }

    @Test
    public void testContainsDuplicates() {
        int[] arrayWithDupes = {1, 2, 3, 4, 4};
        int[] arrayWithNoDupes = {1, 2, 3, 4, 5};
        assertTrue("containsDuplicates method should return 'true'", Library.containsDuplicates(arrayWithDupes));
        assertFalse("containsDuplicates should return 'true'", Library.containsDuplicates(arrayWithNoDupes));
    }


    @Test
    public void testCalculateAverage() {
        int[] arrayOfIntegers = {1, 2, 3, 4, 5};
        assertEquals("Calculate average should return 3.0",3.0, Library.calculateAverage(arrayOfIntegers), 0.001);
    }

    @Test
    public void testFindSmallestAverage() {
        int[][] weeklyMonthTemperatures  = {
                {66, 64, 58, 65, 71, 57, 60},
                {22, 25, 0, 15, 26, 22, 20},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        assertArrayEquals("findSmallestAverage should return {22, 25, 0, 15, 26, 22, 20}", weeklyMonthTemperatures [1], Library.findSmallestAverage(weeklyMonthTemperatures ));
    }
}
