/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Arrays;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static int[] roll(int n) {
        int[] results = new int[n];
        for (int i = 0 ; i < n ; i++) {
            results[i] = (int) (Math.random() * 6) + 1;
        }
        return results;
    }

    public static boolean containsDuplicates(int[] inputArray) {
        Arrays.sort(inputArray);
        for(int i = 1; i < inputArray.length; i++){
            if(inputArray[i - 1] == inputArray[i])
                return true;
        }
        return false;
    }

    public static float calculateAverage(int[] inputArray) {
        int sum = 0;

        for(int num : inputArray) {
            sum += num;
        }

        return sum / inputArray.length;
    }

    public static int[] findSmallestAverage(int[][] inputArrays ) {
        double lowestAverage = calculateAverage(inputArrays[0]);
        int lowestAverageIndex = 0;

        for(int i = 1; i < inputArrays.length; i++) {
            double currentArrayAverage = calculateAverage(inputArrays[i]);
            if( currentArrayAverage < lowestAverage) {
                lowestAverage = currentArrayAverage;
                lowestAverageIndex = i;
            }
        }

        return inputArrays[lowestAverageIndex];
    }

}
